const painSection = document.querySelector(".pain");
if (painSection) {
  painSection.innerHTML = '<div class="narrow"><label>RECONHECE ESSE CICLO?</label><h2>Você monta o aquário, acha que está tudo bem… e do nada começa a perder peixe sem entender o motivo.</h2><p class="section-sub">O pior não é só a perda. É tentar corrigir no escuro, gastar mais dinheiro e ver o problema acontecer de novo.</p><div class="pain-timeline"><article class="pain-step"><span class="pain-number">01</span><h3>Você monta o aquário</h3><p>Faz o básico, organiza tudo e acredita que agora vai dar certo.</p></article><article class="pain-step"><span class="pain-number">02</span><h3>Os peixes parecem bem</h3><p>Nos primeiros dias, tudo parece normal e sob controle.</p></article><article class="pain-step"><span class="pain-number">03</span><h3>Um peixe começa a agir estranho</h3><p>Fica parado, ofegante, escondido ou para de comer.</p></article><article class="pain-step"><span class="pain-number">04</span><h3>Você perde um peixe</h3><p>Não sabe se o problema é água, filtro, temperatura, ciclagem ou outra coisa.</p></article><article class="pain-step"><span class="pain-number">05</span><h3>Você tenta corrigir no escuro</h3><p>Troca água, mexe no filtro, compra produto e tenta adivinhar o que fazer.</p></article><article class="pain-step"><span class="pain-number">06</span><h3>E depois acontece de novo</h3><p>O prejuízo volta porque a causa real nunca foi identificada.</p></article></div><div class="pain-turn">Se isso já aconteceu com você, o problema não é azar. É não ter um <b>protocolo claro</b> para descobrir o que está errado antes de perder o próximo peixe.</div><a class="link pain-cta" href="#oferta">QUERO DESCOBRIR POR ONDE COMEÇAR →</a></div>';
}

const guarantee = document.querySelector(".guarantee");
if (guarantee) {
  guarantee.innerHTML = '<div class="container risk-layout"><div class="risk-seal"><b>7</b><strong>DIAS</strong><small>GARANTIA</small></div><div class="risk-copy"><label>RISCO ZERO PARA TESTAR</label><h2>Você tem 7 dias para acessar o protocolo e ver se ele faz sentido para o seu aquário.</h2><p class="body">Entre agora, veja o material por dentro, consulte o método e use com tranquilidade. Se dentro de 7 dias você perceber que não era o que esperava, poderá solicitar o reembolso dentro do prazo informado no checkout.</p><ul class="risk-benefits"><li>Acesso imediato após a compra</li><li>Leitura fácil pelo celular</li><li>7 dias para testar com tranquilidade</li></ul><p class="risk-close">Você entra com mais segurança e decide com calma.</p></div></div>';
}
